apiVersion: v1
kind: ConfigMap
metadata:
  name: sentiment-config
  namespace: sentiment-analysis
data:
  MODEL_PATH: "/app/models/roberta_sentiment"
  MODEL_NAME: "cardiffnlp/twitter-roberta-base-sentiment"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  GRADIO_HOST: "0.0.0.0"
  GRADIO_PORT: "7860"
  LOG_LEVEL: "INFO"
