apiVersion: v1
kind: Service
metadata:
  name: sentiment-gradio
  namespace: sentiment-analysis
  labels:
    app: sentiment-gradio
    component: frontend
spec:
  type: NodePort
  selector:
    app: sentiment-gradio
  ports:
  - name: http
    port: 7860
    targetPort: 7860
    nodePort: 30786
    protocol: TCP
  sessionAffinity: None
