apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sentiment-analysis

resources:
  - namespace.yaml
  - configmap.yaml
  - api-deployment.yaml
  - api-service.yaml
  - gradio-deployment.yaml
  - gradio-service.yaml

commonLabels:
  project: sentiment-analysis
  managed-by: kustomize
